cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

nursery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', )),
    path('cart/', include('cart.urls', namespace='cart')),
    path('products/', include('products.urls',)),
    path('orders/', include('orders.urls', namespace='orders')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [ 
    path('create/', views.order_create, name='order_create'),
]

products/urls.py
from django.urls import path
from django.urls.conf import include
from django.urls.resolvers import URLPattern

from .views import home, product_detail, product_list

app_name = 'products'

urlpatterns = [ 
    path('', product_list, name='products_list'),
    path('home/', home, name='home' ),
    path('<slug:category_slug>', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce = int)

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     for field in (self.fields['title'], self.fields['body'], self.fields['status']):
    #         fields.widget.attrs.update({'class':'form-control'})

    #     self.fields['image'].widget.attrs.update({'class':'form-control-file'})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cart.forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form']= CartAddProductForm( initial={'quantity': item['quantity'], 'update':True})
    
    return render(request, 'cart/detail.html', {'cart': cart})



# Create your views here.

templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="Viewport" content="width=device-width , initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href='//fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
    <title>
        {% block title %}
        My Shopping Cart
        {% endblock %}
    </title>
</head>


<div class="cart">
    <h1 class="text-white mx-5 py-4"> My Cart </h1>
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>

            </tr>
        </thead>
        </tbody>

        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href=" {{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %} {%endif %}"
                        width="180" height="180">
                </a>
            </td>
            <td> {{ product.name }}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}

                    <input type="submit" value="Update">
                    {% csrf_token %}
                </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}" style="color: red;">Remove</a></td>
            <td class="num">₹{{ item.price }}</td>
            <td class="num">₹{{ item.total_price}}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">₹{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
</div>

<div class="cart-confirm py-4">
    <a href="{% url 'products:products_list' %}" class="continue-btn" style="font-size: 20px;"> Continue
        Shopping </a>
    {% if not user.is_authenticated %}
    <a href="{% url 'login' %}" class="checkout-btn" style="font-size: 20px;">Checkout </a>
    {% else %}
    <a href="{% url 'orders:order_create' %}" class="checkout-btn" style="font-size: 20px;">Checkout </a>

</div>
{% endif %}